from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from PullpayBE import views  # Import views from the correct app

# Create a router and register your viewsets
router = DefaultRouter()
router.register(r"api/transactions", views.TransactionViewSet, basename="transaction")
router.register(r"api/users", views.UserViewSet, basename="user")

urlpatterns = [
    # Admin path
    path("admin/", admin.site.urls),
    # API routes automatically generated by DefaultRouter for ViewSets
    path("", include(router.urls)),  # Includes all the API routes
]
