# Generated by Django 5.1.4 on 2024-12-15 02:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('churchSize', models.PositiveIntegerField()),
                ('denomination', models.CharField(choices=[('CA', 'Catholic'), ('BA', 'Baptist'), ('ME', 'Methodist'), ('PE', 'Pentecostal'), ('ND', 'Non-Denominational'), ('LU', 'Lutheran'), ('PR', 'Presbyterian'), ('OR', 'Orthodox')], default='ND', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('churches', models.ManyToManyField(related_name='members', to='PullpayBE.church')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PullpayBE.user')),
            ],
        ),
    ]
