# Generated by Django 5.1.4 on 2024-12-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PullpayBE', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='churches',
            field=models.ManyToManyField(blank=True, related_name='members', to='PullpayBE.church'),
        ),
    ]
