# Generated by Django 5.1.4 on 2024-12-15 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PullpayBE', '0004_alter_user_churches'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
