# Generated by Django 5.1.4 on 2024-12-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PullpayBE', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='churches',
            field=models.ManyToManyField(blank=True, null=True, related_name='members', to='PullpayBE.church'),
        ),
    ]
